# This is a workflow to demonstrate self hosted runner job processing

name: 'self hosted runner demo'

on: workflow_dispatch

jobs:
  hello-self-hosted-runner:
    runs-on: [self-hosted, Windows, X64, gpu]
    steps:
    - name: run-me-inside-self-hosted-runner
      run: echo "Howdy GitHub Actions. I know I am getting executed inside self hosted runner."

    - name: sleep for 40 seconds
      run: sleep 40
