# What is Github Action?

# An action is a custom application for the Github Actions platform that performs a complex but frequently repeated task. 
# Use an action to help reduce the amount of repetitive code that you write in your workflow files. 

# An action can pull your git repository from Github, set up the correct toolchain for your build environment, or set up the
# authentication to your cloud provider. 


# This is a basic workflow to help you get started with Github Actions. 

name: A Basic Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull requests events but only for the "main" branch
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run specifically or in parallel. 
jobs:
  # This workflow contains a single job called "build"
  build-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under the $GITHUB_WORSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line sript
        run: echo Hello, world!

      # Runs a set of commands using the runner shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building API"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello DB Build"

  packaging:
    needs: [build-app, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "Hello MacOS"



# RUNNER Notes
# A runner is a server that runs your workflows when they're triggered. Each runner can run a single job at a time. 
# Github provides Ubuntu Linux, Microsoft windows, and MacOS runners to run your workflows.
# Each workflow run executes in a fresh, newly-provisioned virtual machine. 

