name: 'Custom ENV Variables'

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Funday
  testvar: value-1

# A workflow run is made up of one or more jobs that can run specifically or in parallel. 
jobs:
  mainjob:
    name: 'Print the environment variables'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2

    steps:
    - name: print-values-of-env-vars
      run: |
        echo "$Greeting $First_name. Today is $DAY_OF_WEEK"
        echo "testvar $testvar"
        echo "testvar ${{ env.testvar}}"
      env:
        First_name: Student
        testvar: value-3
